'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { CalendarDays, Check, ChevronRight, Download, Mail, MessageCircle, Mic2, Paintbrush, PartyPopper, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { addDoc, collection, serverTimestamp } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { jsPDF } from 'jspdf';

type ServiceKey = 'inflable' | 'pintacaritas' | 'animador';
type FormData = { company:string; name:string; hostName:string; celebrantName:string; theme:string; phone:string; email:string; eventType:string; date:string; start:string; end:string; location:string; inflatableSize:string; facePaintCount:string; sound:string; notes:string; total:string; deposit:string; paymentMethod:string };
const initialForm: FormData = { company:'', name:'', hostName:'', celebrantName:'', theme:'', phone:'', email:'', eventType:'', date:'', start:'', end:'', location:'', inflatableSize:'Mediana', facePaintCount:'', sound:'', notes:'', total:'', deposit:'', paymentMethod:'Transferencia' };
const serviceInfo = [
  { key:'inflable' as const, title:'Renta de inflable', copy:'Selecciona el tamaño contratado.', icon:PartyPopper, color:'coral' },
  { key:'pintacaritas' as const, title:'Pintacaritas', copy:'Registra horas o número de niños.', icon:Paintbrush, color:'yellow' },
  { key:'animador' as const, title:'Animador del evento', copy:'Confirma si se incluye equipo de sonido.', icon:Mic2, color:'blue' },
];

function makePdf(form:FormData,services:string[],balance:number,folio:string){
  const pdf=new jsPDF({unit:'mm',format:'a4'}); const navy=[53,32,92] as const; const coral=[217,45,120] as const; const gray=[101,112,131] as const;
  const money=(value:number)=>`$${value.toLocaleString('es-MX',{minimumFractionDigits:2})} MXN`;
  const issued=new Intl.DateTimeFormat('es-MX',{dateStyle:'long'}).format(new Date());
  pdf.setFillColor(...navy);pdf.rect(0,0,210,38,'F');pdf.setFillColor(...coral);pdf.rect(0,38,210,3,'F');
  pdf.setTextColor(255,255,255);pdf.setFont('helvetica','bold');pdf.setFontSize(21);pdf.text('Payasus Fiestas',16,18);pdf.setFontSize(9);pdf.setFont('helvetica','normal');pdf.text('LA DIVERSION EMPIEZA AQUI',16,26);
  pdf.setFont('helvetica','bold');pdf.setFontSize(15);pdf.text('RECIBO DE CONTRATACIÓN',194,17,{align:'right'});pdf.setFontSize(9);pdf.setFont('helvetica','normal');pdf.text(`Folio ${folio}`,194,25,{align:'right'});
  pdf.setTextColor(...navy);pdf.setFont('helvetica','bold');pdf.setFontSize(9);pdf.text('DATOS DEL CLIENTE',16,53);pdf.text('DATOS DE PAYASUS FIESTAS',111,53);
  pdf.setDrawColor(222,226,232);pdf.roundedRect(14,57,87,53,2,2);pdf.roundedRect(109,57,87,53,2,2);
  pdf.setFont('helvetica','normal');pdf.setFontSize(9);pdf.setTextColor(...gray);
  const client=[['Cliente',form.name],['Empresa',form.company||'No aplica'],['Anfitrión',form.hostName],['Teléfono',form.phone],['Correo',form.email||'No proporcionado']];
  const provider=[['Teléfono','55 1276 7519'],['Dirección','Dr. Juan Palomo 12'],['Colonia','Barrio Los Reyes, Tláhuac'],['Fecha de emisión',issued],['Lugar de emisión','Tláhuac, Ciudad de México']];
  const drawRows=(rows:string[][],x:number)=>rows.forEach((row,i)=>{const y=65+i*9;pdf.setFont('helvetica','bold');pdf.setTextColor(...navy);pdf.text(row[0],x,y);pdf.setFont('helvetica','normal');pdf.setTextColor(...gray);const lines=pdf.splitTextToSize(row[1],55);pdf.text(lines,x+25,y)});drawRows(client,19);drawRows(provider,114);
  pdf.setFillColor(245,247,249);pdf.roundedRect(14,119,182,31,2,2,'F');pdf.setFont('helvetica','bold');pdf.setTextColor(...navy);pdf.setFontSize(10);pdf.text('DETALLES DEL EVENTO',19,128);pdf.setFont('helvetica','normal');pdf.setFontSize(9);pdf.text(`Festejado: ${form.celebrantName||'No aplica'}   •   Temática: ${form.theme||'Por definir'}   •   Tipo: ${form.eventType}`,19,137);pdf.text(`Fecha: ${form.date}   •   Horario: ${form.start} a ${form.end}`,19,144);
  pdf.setFont('helvetica','bold');pdf.setFontSize(10);pdf.text('SERVICIOS CONTRATADOS',16,163);pdf.setFillColor(...navy);pdf.rect(14,168,182,10,'F');pdf.setTextColor(255,255,255);pdf.setFontSize(8);pdf.text('CONCEPTO',19,174.5);pdf.text('DETALLE',106,174.5);pdf.text('IMPORTE',190,174.5,{align:'right'});
  let y=187; const details=[...services.map((name,index)=>[name,index===0?(form.notes||'Servicio confirmado'):'Incluido en la contratación']),['Total del servicio','Importe acordado',money(Number(form.total)||0)],['Anticipo recibido',form.paymentMethod,money(Number(form.deposit)||0)]];
  details.forEach((row,index)=>{if(index%2===0){pdf.setFillColor(248,249,250);pdf.rect(14,y-6,182,11,'F')}pdf.setTextColor(...navy);pdf.setFont('helvetica',index>=services.length?'bold':'normal');pdf.setFontSize(9);pdf.text(row[0],19,y);pdf.setFont('helvetica','normal');pdf.setTextColor(...gray);pdf.text(pdf.splitTextToSize(row[1],70),106,y);if(row[2]){pdf.setTextColor(...navy);pdf.setFont('helvetica','bold');pdf.text(row[2],190,y,{align:'right'})}y+=11});
  y=Math.max(y+4,226);pdf.setFillColor(239,252,247);pdf.roundedRect(116,y,80,24,2,2,'F');pdf.setTextColor(...gray);pdf.setFont('helvetica','normal');pdf.setFontSize(9);pdf.text('SALDO PENDIENTE',122,y+8);pdf.setTextColor(18,130,100);pdf.setFont('helvetica','bold');pdf.setFontSize(15);pdf.text(money(balance),190,y+17,{align:'right'});
  pdf.setTextColor(...gray);pdf.setFont('helvetica','normal');pdf.setFontSize(8);pdf.text('El cliente acepta los datos y condiciones registrados en este comprobante. El anticipo reserva la fecha del evento.',16,274);pdf.setDrawColor(...coral);pdf.line(16,281,194,281);pdf.setFont('helvetica','bold');pdf.setTextColor(...navy);pdf.text('Payasus Fiestas  •  55 1276 7519',16,288);pdf.setFont('helvetica','normal');pdf.setTextColor(...gray);pdf.text('Gracias por confiar en nosotros.',194,288,{align:'right'});
  return pdf.output('blob');
}

export default function Home(){
  const [services,setServices]=useState<ServiceKey[]>([]); const [form,setForm]=useState(initialForm); const [submitted,setSubmitted]=useState(false); const [accepted,setAccepted]=useState(false); const [error,setError]=useState(''); const [saving,setSaving]=useState(false); const [folio,setFolio]=useState('');
  const selectedNames=useMemo(()=>serviceInfo.filter(s=>services.includes(s.key)).map(s=>s.title),[services]);
  const setField=(key:keyof FormData,value:string)=>setForm(current=>({...current,[key]:value}));
  const toggleService=(key:ServiceKey)=>setServices(current=>current.includes(key)?current.filter(item=>item!==key):[...current,key]);
  useEffect(()=>{if('serviceWorker'in navigator){navigator.serviceWorker.register('/sw.js').catch(()=>undefined)}},[]);
  useEffect(()=>{
    const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;
    if(!context?.registerTool)return;
    const lifecycle=new AbortController();
    void Promise.resolve(context.registerTool({name:'prepare_event_request',title:'Preparar solicitud de evento',description:'Completa el formulario visible con los datos del cliente, evento y servicios seleccionados.',inputSchema:{type:'object',properties:{company:{type:'string'},name:{type:'string'},hostName:{type:'string'},celebrantName:{type:'string'},theme:{type:'string'},phone:{type:'string'},email:{type:'string'},eventType:{type:'string'},date:{type:'string'},start:{type:'string'},end:{type:'string'},location:{type:'string'},services:{type:'array',items:{type:'string',enum:['inflable','pintacaritas','animador']},minItems:1,uniqueItems:true}},required:['name','hostName','phone','eventType','date','start','end','location','services'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const data=input as Partial<FormData>&{services?:ServiceKey[]};if(!data.name||!data.hostName||!data.phone||!data.eventType||!data.date||!data.start||!data.end||!data.location||!data.services?.length)throw new Error('Faltan datos obligatorios de la solicitud.');setForm(current=>({...current,...data}));setServices(data.services);setSubmitted(false);setError('');document.getElementById('solicitud')?.scrollIntoView({behavior:'smooth'});return {status:'prepared',services:data.services};}},{signal:lifecycle.signal})).catch(()=>undefined);
    return()=>lifecycle.abort();
  },[]);
  const balance=Math.max(0,(Number(form.total)||0)-(Number(form.deposit)||0));
  const receiptBlob=()=>makePdf(form,selectedNames,balance,folio||`FIE-${Date.now().toString().slice(-6)}`);
  const downloadPdf=()=>{const url=URL.createObjectURL(receiptBlob());const anchor=document.createElement('a');anchor.href=url;anchor.download=`recibo-payasus-fiestas-${folio||'evento'}.pdf`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
  const sharePdf=async()=>{const file=new File([receiptBlob()],`recibo-payasus-fiestas-${folio||'evento'}.pdf`,{type:'application/pdf'});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title:'Recibo de contratación Payasus Fiestas',text:`Hola ${form.name}, te comparto el recibo de tu evento.`,files:[file]})}else{downloadPdf();window.open(`https://wa.me/${form.phone.replace(/\D/g,'')}?text=${encodeURIComponent(`Hola ${form.name}, te comparto tu recibo de contratación Payasus Fiestas. El PDF se descargó para adjuntarlo en este chat.`)}`,'_blank')}};
  const handleSubmit=async(event:FormEvent)=>{event.preventDefault();if(!services.length){setError('Selecciona al menos un servicio para continuar.');return}if(!accepted){setError('Pide al cliente aceptar las condiciones para cerrar la contratación.');return}setError('');setSaving(true);try{const ref=await addDoc(collection(db,'contrataciones'),{...form,marca:'payasus',sourceProject:'payasus-fiestas',services,total:Number(form.total),deposit:Number(form.deposit),balance,accepted:true,status:'confirmada',createdAt:serverTimestamp()});setFolio('PAY-'+ref.id.slice(0,8).toUpperCase());setSubmitted(true);window.setTimeout(()=>document.getElementById('confirmacion')?.scrollIntoView({behavior:'smooth',block:'center'}),40)}catch{setError('No fue posible guardar la contratación. Verifica la conexión e inténtalo nuevamente.')}finally{setSaving(false)}};
  return <main className="min-h-screen bg-[#f6f5f9] text-[#35205c]">
    <header className="border-b border-[#35205c]/10 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-3 sm:px-8"><a href="#inicio" className="flex items-center gap-3 font-black tracking-tight"><img src="/payasus-fiestas-icon.svg" alt="" className="size-9 rounded-xl"/><span>Payasus Fiestas</span></a><span className="rounded-lg bg-[#f3eff9] px-3 py-2 text-xs font-bold text-[#695581]">Panel del asesor</span></div></header>
    <section id="inicio" className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3 px-5 py-6 sm:px-8"><div><h1 className="text-2xl font-black tracking-tight sm:text-3xl">Cierre de venta</h1><p className="mt-1 text-sm text-[#6b7485]">Captura el acuerdo con el cliente, registra el anticipo y entrega su recibo.</p></div><span className="rounded-full border border-[#35205c]/15 bg-white px-3 py-2 text-xs font-bold">{submitted?'Contratación guardada':'Nueva contratación'}</span></section>
    <form id="solicitud" onSubmit={handleSubmit} className="mx-auto max-w-7xl px-5 pb-10 sm:px-8"><div className="mb-3 flex flex-wrap items-end justify-between gap-2"><div><p className="text-sm font-black uppercase tracking-[.18em] text-[#d92d78]">01 · Servicios</p><h2 className="mt-1 text-lg font-black tracking-tight">Servicios contratados</h2></div><p className="hidden max-w-xs text-right text-sm text-[#6b7485] md:block">Marca los servicios incluidos en el acuerdo.</p></div>
      <div className="grid gap-3 md:grid-cols-3">{serviceInfo.map(({key,title,copy,icon:Icon,color})=>{const active=services.includes(key);const bg=color==='coral'?'bg-[#fce7f3]':color==='yellow'?'bg-[#fff8d8]':'bg-[#eaf8fc]';return <button key={key} type="button" onClick={()=>toggleService(key)} aria-pressed={active} className={`group relative rounded-xl border-2 p-4 text-left transition-colors ${active?'border-[#35205c] bg-[#f3eff9]':'border-transparent '+bg}`}><div className="flex items-start justify-between"><span className="grid size-9 place-items-center rounded-lg bg-white"><Icon/></span><span aria-hidden="true" className={`grid size-5 place-items-center rounded border ${active?'border-[#35205c] bg-[#35205c] text-white':'border-[#9a90a8] bg-white'}`}>{active&&<Check size={14}/>}</span></div><h3 className="mt-3 text-base font-bold">{title}</h3><p className="mt-1 text-xs leading-5 text-[#657083]">{copy}</p></button>})}</div>{error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{error}</p>}
      <div className="mt-5 grid items-start gap-5 lg:grid-cols-[minmax(0,1fr)_320px]"><section className="min-w-0 rounded-xl border border-[#35205c]/10 bg-white p-5 sm:p-6"><p className="text-sm font-black uppercase tracking-[.18em] text-[#d92d78]">02 · Cliente y evento</p><h2 className="mt-1 text-xl font-black tracking-tight">Datos de la contratación</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">
        <Field label="Empresa" hint="Opcional"><Input value={form.company} onChange={e=>setField('company',e.target.value)} placeholder="Nombre de la empresa o institución"/></Field><Field label="Nombre del anfitrión" required><Input required value={form.hostName} onChange={e=>setField('hostName',e.target.value)} placeholder="Persona responsable del evento"/></Field><Field label="Nombre del cliente" required><Input required value={form.name} onChange={e=>setField('name',e.target.value)} placeholder="Ej. Mariana López"/></Field><Field label="Nombre del festejado" hint="Opcional"><Input value={form.celebrantName} onChange={e=>setField('celebrantName',e.target.value)} placeholder="Ej. Sofía"/></Field><Field label="Temática" hint="Opcional"><Input value={form.theme} onChange={e=>setField('theme',e.target.value)} placeholder="Ej. Princesas, dinosaurios…"/></Field><Field label="Teléfono / WhatsApp" required><Input required type="tel" value={form.phone} onChange={e=>setField('phone',e.target.value)} placeholder="55 1234 5678"/></Field><Field label="Correo electrónico" hint="Opcional"><Input type="email" value={form.email} onChange={e=>setField('email',e.target.value)} placeholder="nombre@correo.com"/></Field><Field label="Tipo de evento" required><select required value={form.eventType} onChange={e=>setField('eventType',e.target.value)} className="field-control"><option value="">Selecciona una opción</option><option>Fiesta infantil</option><option>Cumpleaños</option><option>XV años</option><option>Bautizo</option><option>Evento escolar</option><option>Evento empresarial</option><option>Otro</option></select></Field><Field label="Fecha del evento" required><Input required type="date" min={new Date().toISOString().split('T')[0]} value={form.date} onChange={e=>setField('date',e.target.value)}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Inicio" required><Input required type="time" value={form.start} onChange={e=>setField('start',e.target.value)}/></Field><Field label="Término" required><Input required type="time" value={form.end} onChange={e=>setField('end',e.target.value)}/></Field></div><Field label="Ubicación o alcaldía / municipio" required wide><Input required value={form.location} onChange={e=>setField('location',e.target.value)} placeholder="Ej. Coyoacán, CDMX"/></Field></div>
        {services.length>0&&<div className="mt-6 border-t border-[#35205c]/10 pt-6"><h3 className="text-xl font-black">Especificaciones del servicio</h3><div className="mt-5 grid gap-5 sm:grid-cols-2">{services.includes('inflable')&&<Field label="Tamaño del inflable"><select className="field-control" value={form.inflatableSize} onChange={e=>setField('inflatableSize',e.target.value)}><option>Chica</option><option>Mediana</option><option>Grande</option></select></Field>}{services.includes('pintacaritas')&&<Field label="Horas o número aproximado de niños"><Input value={form.facePaintCount} onChange={e=>setField('facePaintCount',e.target.value)} placeholder="Ej. 2 horas / 25 niños"/></Field>}{services.includes('animador')&&<div className="sm:col-span-2"><p className="mb-3 text-sm font-bold">¿Cuentan con bocina y micrófono?</p><RadioGroup value={form.sound} onValueChange={value=>setField('sound',String(value))} className="grid gap-3 sm:grid-cols-2"><label className="flex cursor-pointer items-center gap-3 rounded-xl border p-4"><RadioGroupItem value="Sí, ya hay equipo en el lugar"/><span className="text-sm font-semibold">Sí, ya hay equipo en el lugar</span></label><label className="flex cursor-pointer items-center gap-3 rounded-xl border p-4"><RadioGroupItem value="No, requiero que lo incluyan"/><span className="text-sm font-semibold">No, requiero que lo incluyan</span></label></RadioGroup></div>}</div></div>}
        <div className="mt-7"><Field label="Comentarios adicionales" hint="Opcional"><Textarea value={form.notes} onChange={e=>setField('notes',e.target.value)} placeholder="Acuerdos especiales, acceso al lugar o indicaciones…" className="min-h-28"/></Field></div>
        <div className="mt-6 border-t border-[#35205c]/10 pt-6"><h3 className="text-xl font-black">03 · Pago y aceptación</h3><div className="mt-5 grid gap-5 sm:grid-cols-3"><Field label="Total acordado" required><Input required type="number" min="0" inputMode="decimal" value={form.total} onChange={e=>setField('total',e.target.value)} placeholder="$ 0.00"/></Field><Field label="Anticipo recibido" required><Input required type="number" min="0" inputMode="decimal" value={form.deposit} onChange={e=>setField('deposit',e.target.value)} placeholder="$ 0.00"/></Field><Field label="Forma de pago" required><select className="field-control" value={form.paymentMethod} onChange={e=>setField('paymentMethod',e.target.value)}><option>Transferencia</option><option>Efectivo</option><option>Tarjeta</option><option>Otro</option></select></Field></div><label className="mt-6 flex cursor-pointer items-start gap-3 rounded-2xl bg-[#f5f7f9] p-4"><Checkbox checked={accepted} onCheckedChange={value=>setAccepted(Boolean(value))} className="mt-1 size-5"/><span className="text-sm leading-6"><strong>El cliente acepta la contratación y los datos capturados.</strong><br/><span className="text-[#687284]">El anticipo reserva la fecha; el saldo y cualquier condición especial quedan registrados en este recibo.</span></span></label></div></section>
        <aside className="min-w-0 h-fit rounded-xl bg-[#35205c] p-5 text-white lg:sticky lg:top-5"><p className="text-sm font-black uppercase tracking-[.18em] text-[#ffd54a]">Resumen de cierre</p><h3 className="mt-2 text-2xl font-black">Revisión de la venta</h3><div className="my-6 space-y-3 border-y border-white/15 py-5">{selectedNames.length?selectedNames.map(name=><div key={name} className="flex items-center gap-3 text-sm"><span className="grid size-6 place-items-center rounded-full bg-[#18a981]"><Check size={14}/></span>{name}</div>):<p className="text-sm leading-6 text-white/65">Selecciona los servicios contratados.</p>}<dl className="space-y-3 border-t border-white/15 pt-4 text-sm"><div><dt className="text-xs text-white/60">Cliente</dt><dd className="mt-1 break-words font-bold">{form.name||'Sin capturar'}</dd></div><div><dt className="flex items-center gap-1 text-xs text-white/60"><CalendarDays size={13}/> Fecha y horario</dt><dd className="mt-1 font-bold">{form.date||'Sin capturar'}{form.start&&` · ${form.start}`}{form.end&&` a ${form.end}`}</dd></div></dl><dl className="space-y-3 border-t border-white/15 pt-4 text-sm"><div className="flex justify-between gap-3"><dt className="text-white/70">Total acordado</dt><dd className="font-bold">${(Number(form.total)||0).toLocaleString('es-MX')} MXN</dd></div><div className="flex justify-between gap-3"><dt className="text-white/70">Anticipo recibido</dt><dd className="font-bold">${(Number(form.deposit)||0).toLocaleString('es-MX')} MXN</dd></div><div className="border-t border-white/15 pt-3"><dt className="text-xs text-white/70">Saldo pendiente</dt><dd className="mt-1 text-2xl font-black">${balance.toLocaleString('es-MX')} <span className="text-sm">MXN</span></dd></div></dl></div><Button type="submit" className="h-12 w-full rounded-xl bg-[#d92d78] text-base font-black hover:bg-[#b91e64]" disabled={saving}>{saving?'Guardando contratación…':<>Guardar y generar recibo <ChevronRight/></>}</Button><p className="mt-4 flex items-start gap-2 text-xs leading-5 text-white/55"><ShieldCheck className="mt-0.5 shrink-0" size={15}/> Revisa los datos con el cliente antes de confirmar.</p></aside></div>
      {submitted&&<section id="confirmacion" className="mt-10 scroll-mt-8 rounded-[2rem] border-2 border-[#18a981] bg-[#effcf7] p-6 sm:p-9" aria-live="polite"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-center"><div className="flex gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-full bg-[#18a981] text-white"><Check size={25}/></span><div><p className="text-sm font-black uppercase tracking-widest text-[#128264]">Contratación confirmada</p><h2 className="mt-1 text-2xl font-black">Entrega el recibo ahora</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[#4d6860]">Toca “Enviar recibo” en la tablet y elige WhatsApp o Mail: el PDF irá adjunto. También puedes descargar una copia.</p></div></div><div className="flex flex-wrap gap-3 md:justify-end"><Button type="button" variant="outline" className="h-11 bg-white" onClick={downloadPdf}><Download/> Descargar copia</Button><Button type="button" className="h-12 bg-[#18a981] px-5 text-base font-black hover:bg-[#128264]" onClick={sharePdf}><MessageCircle/> Enviar recibo</Button>{form.email&&<a className="inline-flex h-11 items-center gap-2 rounded-lg border bg-white px-3 text-sm font-bold" href={`mailto:${encodeURIComponent(form.email)}?subject=${encodeURIComponent('Tu recibo de contratación')}&body=${encodeURIComponent(`Hola ${form.name}, te compartimos tu recibo de contratación. Adjunta el PDF descargado a este correo.`)}`}><Mail size={16}/> Abrir Mail</a>}</div></div></section>}
    </form><footer className="border-t border-[#35205c]/10 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-2 px-5 py-4 text-xs text-[#6b7485] sm:flex-row sm:flex-wrap sm:items-center sm:justify-between sm:px-8"><p className="font-bold text-[#35205c]">Payasus Fiestas</p><p>Inflables · Pintacaritas · Animación</p><a href="tel:+525512767519" className="font-bold">55 1276 7519</a><p>Dr. Juan Palomo 12 · Barrio Los Reyes, Tláhuac</p></div></footer>
  </main>
}
function Field({label,hint,required,wide,children}:{label:string;hint?:string;required?:boolean;wide?:boolean;children:React.ReactNode}){return <label className={wide?'sm:col-span-2':''}><span className="mb-2 flex items-center gap-2 text-sm font-bold">{label}{required&&<span className="text-[#d92d78]">*</span>}{hint&&<span className="font-normal text-[#9299a6]">{hint}</span>}</span>{children}</label>}





